name: go_router_examples
description: go_router examples
version: 1.1.3
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  adaptive_navigation: ^0.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router:
    path: ..
  provider: ^5.0.0
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
